"""add_share

Revision ID: 0e07182b84de
Revises: eed984b8e42c
Create Date: 2026-02-28 19:31:33.180254

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "0e07182b84de"
down_revision: str | Sequence[str] | None = "eed984b8e42c"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "share_batches",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("company_id", sa.UUID(), nullable=False),
        sa.Column("owner_id", sa.UUID(), nullable=False),
        sa.Column("share_type", sa.Enum("LINK", "USER", name="sharetype", native_enum=False), nullable=False),
        sa.Column("share_token", sa.Text(), nullable=True),
        sa.Column("link_password_hash", sa.Text(), nullable=True),
        sa.Column("shared_with_user_id", sa.UUID(), nullable=True),
        sa.Column("message", sa.Text(), nullable=True),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("is_active", sa.Boolean(), server_default="true", nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(["company_id"], ["companies.id"], name=op.f("fk_share_batches_company_id_companies"), ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["owner_id"], ["users.id"], name=op.f("fk_share_batches_owner_id_users"), ondelete="CASCADE"),
        sa.ForeignKeyConstraint(
            ["shared_with_user_id"], ["users.id"], name=op.f("fk_share_batches_shared_with_user_id_users"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_share_batches")),
    )
    op.create_index(op.f("ix_share_batches_company_id"), "share_batches", ["company_id"], unique=False)
    op.create_index(op.f("ix_share_batches_expires_at"), "share_batches", ["expires_at"], unique=False)
    op.create_index(op.f("ix_share_batches_is_active"), "share_batches", ["is_active"], unique=False)
    op.create_index(op.f("ix_share_batches_owner_id"), "share_batches", ["owner_id"], unique=False)
    op.create_index(op.f("ix_share_batches_share_token"), "share_batches", ["share_token"], unique=True)
    op.create_index(op.f("ix_share_batches_shared_with_user_id"), "share_batches", ["shared_with_user_id"], unique=False)
    op.create_table(
        "document_shares",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("batch_id", sa.UUID(), nullable=False),
        sa.Column("document_id", sa.UUID(), nullable=True),
        sa.Column("folder_id", sa.UUID(), nullable=True),
        sa.Column("permission_level", sa.Enum("VIEW", "EDIT", name="permissionlevel", native_enum=False), nullable=False),
        sa.Column("can_download", sa.Boolean(), server_default="true", nullable=False),
        sa.CheckConstraint(
            "(document_id IS NOT NULL AND folder_id IS NULL) OR (document_id IS NULL AND folder_id IS NOT NULL)",
            name=op.f("ck_document_shares_ck_document_shares_resource_presence"),
        ),
        sa.ForeignKeyConstraint(["batch_id"], ["share_batches.id"], name=op.f("fk_document_shares_batch_id_share_batches"), ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["document_id"], ["documents.id"], name=op.f("fk_document_shares_document_id_documents"), ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["folder_id"], ["folders.id"], name=op.f("fk_document_shares_folder_id_folders"), ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_document_shares")),
    )
    op.create_index("ix_doc_share_resource_lookup", "document_shares", ["document_id", "folder_id"], unique=False)
    op.create_index(op.f("ix_document_shares_batch_id"), "document_shares", ["batch_id"], unique=False)
    op.create_index(op.f("ix_document_shares_document_id"), "document_shares", ["document_id"], unique=False)
    op.create_index(op.f("ix_document_shares_folder_id"), "document_shares", ["folder_id"], unique=False)
    op.create_table(
        "share_access_logs",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("batch_id", sa.UUID(), nullable=False),
        sa.Column(
            "access_type",
            sa.Enum("VIEW", "DOWNLOAD", "PREVIEW", name="shareaccesstype", native_enum=False),
            server_default="view",
            nullable=False,
        ),
        sa.Column("accessed_by_user_id", sa.UUID(), nullable=True),
        sa.Column("ip_address", sa.Text(), nullable=True),
        sa.Column("user_agent", sa.Text(), nullable=True),
        sa.Column("accessed_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(["batch_id"], ["share_batches.id"], name=op.f("fk_share_access_logs_batch_id_share_batches"), ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_share_access_logs")),
    )
    op.create_index(op.f("ix_share_access_logs_access_type"), "share_access_logs", ["access_type"], unique=False)
    op.create_index(op.f("ix_share_access_logs_accessed_at"), "share_access_logs", ["accessed_at"], unique=False)
    op.create_index(op.f("ix_share_access_logs_batch_id"), "share_access_logs", ["batch_id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_share_access_logs_batch_id"), table_name="share_access_logs")
    op.drop_index(op.f("ix_share_access_logs_accessed_at"), table_name="share_access_logs")
    op.drop_index(op.f("ix_share_access_logs_access_type"), table_name="share_access_logs")
    op.drop_table("share_access_logs")
    op.drop_index(op.f("ix_document_shares_folder_id"), table_name="document_shares")
    op.drop_index(op.f("ix_document_shares_document_id"), table_name="document_shares")
    op.drop_index(op.f("ix_document_shares_batch_id"), table_name="document_shares")
    op.drop_index("ix_doc_share_resource_lookup", table_name="document_shares")
    op.drop_table("document_shares")
    op.drop_index(op.f("ix_share_batches_shared_with_user_id"), table_name="share_batches")
    op.drop_index(op.f("ix_share_batches_share_token"), table_name="share_batches")
    op.drop_index(op.f("ix_share_batches_owner_id"), table_name="share_batches")
    op.drop_index(op.f("ix_share_batches_is_active"), table_name="share_batches")
    op.drop_index(op.f("ix_share_batches_expires_at"), table_name="share_batches")
    op.drop_index(op.f("ix_share_batches_company_id"), table_name="share_batches")
    op.drop_table("share_batches")
    # ### end Alembic commands ###
