"""add root folder for case

Revision ID: 12ecb4367fc3
Revises: f48b31059f9a
Create Date: 2026-02-23 20:29:48.377087

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "12ecb4367fc3"
down_revision: str | Sequence[str] | None = "f48b31059f9a"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("cases", sa.Column("root_folder_id", sa.UUID(), nullable=True))
    op.create_index(op.f("ix_cases_root_folder_id"), "cases", ["root_folder_id"], unique=True)
    op.create_foreign_key(op.f("fk_cases_root_folder_id_folders"), "cases", "folders", ["root_folder_id"], ["id"], ondelete="SET NULL")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f("fk_cases_root_folder_id_folders"), "cases", type_="foreignkey")
    op.drop_index(op.f("ix_cases_root_folder_id"), table_name="cases")
    op.drop_column("cases", "root_folder_id")
    # ### end Alembic commands ###
