"""add email_contacts table

Revision ID: 1405121c5549
Revises: 59504b913936
Create Date: 2026-03-16 17:41:34.308666

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "1405121c5549"
down_revision: str | Sequence[str] | None = "59504b913936"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "email_contacts",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("email", sa.String(length=255), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=True),
        sa.Column("source", sa.Enum("CLIENT", "SENT", "RECEIVED", name="emailcontactsource", native_enum=False), nullable=False),
        sa.Column("usage_count", sa.Integer(), server_default="0", nullable=False),
        sa.Column("last_used_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("company_id", sa.UUID(), nullable=True),
        sa.ForeignKeyConstraint(["company_id"], ["companies.id"], name=op.f("fk_email_contacts_company_id_companies"), ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_email_contacts")),
        sa.UniqueConstraint("company_id", "email", name="uq_email_contacts_company_email"),
    )
    op.create_index(op.f("ix_email_contacts_company_id"), "email_contacts", ["company_id"], unique=False)
    op.create_index(
        "ix_email_contacts_email_prefix", "email_contacts", ["company_id", "email"], unique=False, postgresql_ops={"email": "text_pattern_ops"}
    )
    op.create_index(
        "ix_email_contacts_name_prefix", "email_contacts", ["company_id", "name"], unique=False, postgresql_ops={"name": "text_pattern_ops"}
    )
    op.create_index("ix_email_contacts_usage", "email_contacts", ["company_id", "usage_count", "last_used_at"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_email_contacts_usage", table_name="email_contacts")
    op.drop_index("ix_email_contacts_name_prefix", table_name="email_contacts", postgresql_ops={"name": "text_pattern_ops"})
    op.drop_index("ix_email_contacts_email_prefix", table_name="email_contacts", postgresql_ops={"email": "text_pattern_ops"})
    op.drop_index(op.f("ix_email_contacts_company_id"), table_name="email_contacts")
    op.drop_table("email_contacts")
    # ### end Alembic commands ###
