"""update Document atributcase id

Revision ID: 2d7ad9e973ee
Revises: ebc8060eb98a
Create Date: 2026-01-22 10:03:03.502610

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "2d7ad9e973ee"
down_revision: str | Sequence[str] | None = "ebc8060eb98a"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("documents", "case_id", existing_type=sa.UUID(), nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("documents", "case_id", existing_type=sa.UUID(), nullable=False)
    # ### end Alembic commands ###
