"""add company model

Revision ID: 40aad378fece
Revises: f833aefbc52a
Create Date: 2026-01-27 19:53:11.873598

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "40aad378fece"
down_revision: str | Sequence[str] | None = "f833aefbc52a"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "companies",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("inn", sa.String(length=12), nullable=False),
        sa.Column("email", sa.String(length=255), nullable=True),
        sa.Column("phone", sa.String(length=50), nullable=True),
        sa.Column(
            "balance", sa.Numeric(precision=15, scale=2), server_default="0.00", nullable=False, comment="Текущий баланс компании на счету"
        ),
        sa.Column("currency", sa.String(length=3), server_default="RUB", nullable=False),
        sa.Column("is_active", sa.Boolean(), server_default="true", nullable=False),
        sa.Column("is_trial", sa.Boolean(), server_default="true", nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_companies")),
    )
    op.create_index(op.f("ix_companies_inn"), "companies", ["inn"], unique=True)
    op.create_index(op.f("ix_companies_name"), "companies", ["name"], unique=False)
    op.add_column("users", sa.Column("company_id", sa.UUID(), nullable=False))
    op.create_foreign_key(op.f("fk_users_company_id_companies"), "users", "companies", ["company_id"], ["id"], ondelete="CASCADE")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f("fk_users_company_id_companies"), "users", type_="foreignkey")
    op.drop_column("users", "company_id")
    op.drop_index(op.f("ix_companies_name"), table_name="companies")
    op.drop_index(op.f("ix_companies_inn"), table_name="companies")
    op.drop_table("companies")
    # ### end Alembic commands ###
