"""fix table

Revision ID: 4c25d7102237
Revises: b77e4c662fb4
Create Date: 2026-01-23 19:12:55.451754

"""

from collections.abc import Sequence

# revision identifiers, used by Alembic.
revision: str = "4c25d7102237"
down_revision: str | Sequence[str] | None = "b77e4c662fb4"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
