"""Add registration_date to cases

Revision ID: 51030402f484
Revises: bbb57d4bb023
Create Date: 2026-05-21 15:43:01.328811

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "51030402f484"
down_revision: str | Sequence[str] | None = "bbb57d4bb023"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("cases", sa.Column("registration_date", sa.DateTime(timezone=True), nullable=True))
    op.create_index(op.f("ix_cases_registration_date"), "cases", ["registration_date"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_cases_registration_date"), table_name="cases")
    op.drop_column("cases", "registration_date")
    # ### end Alembic commands ###
