"""initial_migration

Revision ID: 57db10d915a6
Revises:
Create Date: 2026-02-09 21:29:18.005647

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "57db10d915a6"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "companies",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("name", sa.Text(), nullable=False),
        sa.Column("inn", sa.String(length=12), nullable=False),
        sa.Column("email", sa.String(length=255), nullable=True),
        sa.Column("phone", sa.String(length=50), nullable=True),
        sa.Column("balance", sa.Numeric(precision=15, scale=2), server_default="0.00", nullable=False),
        sa.Column("currency", sa.String(length=3), server_default="RUB", nullable=False),
        sa.Column("is_active", sa.Boolean(), server_default="true", nullable=False),
        sa.Column("is_trial", sa.Boolean(), server_default="true", nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_companies")),
    )
    op.create_index(op.f("ix_companies_inn"), "companies", ["inn"], unique=True)
    op.create_index(op.f("ix_companies_name"), "companies", ["name"], unique=False)
    op.create_table(
        "clients",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("company_id", sa.UUID(), nullable=False),
        sa.Column("name", sa.Text(), nullable=False),
        sa.Column("short_name", sa.Text(), nullable=True),
        sa.Column("type", sa.Enum("legal", "individual", "court", name="clienttype", native_enum=False), nullable=False),
        sa.Column("inn", sa.String(length=12), nullable=True),
        sa.Column("email", sa.String(length=255), nullable=True),
        sa.Column("phone", sa.String(length=50), nullable=True),
        sa.Column("legal_address", sa.Text(), nullable=True),
        sa.Column("actual_address", sa.Text(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(["company_id"], ["companies.id"], name=op.f("fk_clients_company_id_companies"), ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_clients")),
    )
    op.create_index(op.f("ix_clients_company_id"), "clients", ["company_id"], unique=False)
    op.create_index(op.f("ix_clients_inn"), "clients", ["inn"], unique=True)
    op.create_index(op.f("ix_clients_name"), "clients", ["name"], unique=False)
    op.create_index("ix_clients_name_prefix", "clients", ["name"], unique=False, postgresql_ops={"name": "text_pattern_ops"})
    op.create_index("ix_clients_short_name_prefix", "clients", ["short_name"], unique=False, postgresql_ops={"short_name": "text_pattern_ops"})
    op.create_table(
        "users",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("email", sa.String(length=255), nullable=False),
        sa.Column("hashed_password", sa.Text(), nullable=False),
        sa.Column("full_name", sa.Text(), nullable=False),
        sa.Column("role", sa.Enum("ADMIN", "CEO", "ACCOUNTANT", "EXPERT", name="userrole", native_enum=False), nullable=False),
        sa.Column("is_active", sa.Boolean(), server_default="false", nullable=False),
        sa.Column("can_authenticate", sa.Boolean(), server_default="true", nullable=False),
        sa.Column("last_login", sa.DateTime(timezone=True), nullable=True),
        sa.Column("settings", sa.JSON(), server_default="{}", nullable=False),
        sa.Column("specialization", sa.Text(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("company_id", sa.UUID(), nullable=False),
        sa.ForeignKeyConstraint(["company_id"], ["companies.id"], name=op.f("fk_users_company_id_companies"), ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_users")),
    )
    op.create_index(op.f("ix_users_email"), "users", ["email"], unique=True)
    op.create_index("ix_users_full_name_prefix", "users", ["full_name"], unique=False, postgresql_ops={"full_name": "text_pattern_ops"})
    op.create_table(
        "cases",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("client_id", sa.UUID(), nullable=False),
        sa.Column("number", sa.String(length=50), nullable=False),
        sa.Column("case_number", sa.String(length=100), nullable=False),
        sa.Column("authority", sa.Text(), nullable=False),
        sa.Column("case_type", sa.Text(), nullable=False),
        sa.Column("object_type", sa.Text(), nullable=False),
        sa.Column("object_address", sa.Text(), nullable=False),
        sa.Column(
            "status",
            sa.Enum("archive", "in_work", "debt", "executed", "withdrawn", "cancelled", "fssp", name="casestatus", native_enum=False),
            nullable=False,
        ),
        sa.Column("assigned_user_id", sa.Uuid(), nullable=True),
        sa.Column("start_date", sa.DateTime(timezone=True), nullable=False),
        sa.Column("deadline", sa.DateTime(timezone=True), nullable=False),
        sa.Column("completion_date", sa.DateTime(timezone=True), nullable=True),
        sa.Column("cost", sa.Numeric(precision=12, scale=2), nullable=False),
        sa.Column("bank_transfer_amount", sa.Numeric(precision=12, scale=2), server_default="0.00", nullable=False),
        sa.Column("cash_amount", sa.Numeric(precision=12, scale=2), server_default="0.00", nullable=False),
        sa.Column("remaining_debt", sa.Numeric(precision=12, scale=2), server_default="0.00", nullable=False),
        sa.Column("plaintiff", sa.Text(), nullable=True),
        sa.Column("defendant", sa.Text(), nullable=True),
        sa.Column("expert_painting", sa.Text(), nullable=True),
        sa.Column("archive_status", sa.Text(), nullable=True),
        sa.Column("remarks", sa.Text(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(["assigned_user_id"], ["users.id"], name=op.f("fk_cases_assigned_user_id_users"), ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["client_id"], ["clients.id"], name=op.f("fk_cases_client_id_clients"), ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_cases")),
    )
    op.create_index(op.f("ix_cases_case_number"), "cases", ["case_number"], unique=True)
    op.create_index("ix_cases_case_number_btree", "cases", ["case_number"], unique=False)
    op.create_index("ix_cases_client_status", "cases", ["client_id", "status"], unique=False)
    op.create_index(op.f("ix_cases_deadline"), "cases", ["deadline"], unique=False)
    op.create_index(op.f("ix_cases_deleted_at"), "cases", ["deleted_at"], unique=False)
    op.create_index(op.f("ix_cases_number"), "cases", ["number"], unique=True)
    op.create_index("ix_cases_number_btree", "cases", ["number"], unique=False)
    op.create_index(op.f("ix_cases_status"), "cases", ["status"], unique=False)
    op.create_table(
        "contacts",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("client_id", sa.UUID(), nullable=False),
        sa.Column("name", sa.Text(), nullable=False),
        sa.Column("position", sa.Text(), nullable=True),
        sa.Column("email", sa.String(length=255), nullable=True),
        sa.Column("phone", sa.String(length=50), nullable=True),
        sa.Column("is_main", sa.Boolean(), server_default="false", nullable=False),
        sa.Column(
            "contact_type", sa.Enum("legal_representative", "court_officer", "individual", name="contacttype", native_enum=False), nullable=False
        ),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(["client_id"], ["clients.id"], name=op.f("fk_contacts_client_id_clients"), ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_contacts")),
    )
    op.create_table(
        "user_email_configs",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("smtp_host", sa.Text(), nullable=False),
        sa.Column("smtp_port", sa.Integer(), nullable=False),
        sa.Column("smtp_user", sa.Text(), nullable=False),
        sa.Column("smtp_password", sa.Text(), nullable=False),
        sa.Column("imap_host", sa.Text(), nullable=False),
        sa.Column("imap_port", sa.Integer(), nullable=False),
        sa.Column("imap_user", sa.Text(), nullable=False),
        sa.Column("imap_password", sa.Text(), nullable=False),
        sa.Column("last_sync_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("sync_enabled", sa.Boolean(), server_default="true", nullable=False),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], name=op.f("fk_user_email_configs_user_id_users"), ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_user_email_configs")),
        sa.UniqueConstraint("user_id", name=op.f("uq_user_email_configs_user_id")),
    )
    op.create_table(
        "calendar_activities",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("type", sa.Enum("EVENT", "TASK", name="activitytype", native_enum=False), nullable=False),
        sa.Column("company_id", sa.UUID(), nullable=False),
        sa.Column("creator_id", sa.Uuid(), nullable=True),
        sa.Column("title", sa.Text(), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("color", sa.String(length=20), nullable=True),
        sa.Column("start_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("end_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("all_day", sa.Boolean(), nullable=False),
        sa.Column("is_completed", sa.Boolean(), nullable=False),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("location", sa.Text(), nullable=True),
        sa.Column("status", sa.Enum("SCHEDULED", "CANCELLED", name="eventstatus", native_enum=False), nullable=False),
        sa.Column("case_id", sa.UUID(), nullable=True),
        sa.Column("client_id", sa.UUID(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(["case_id"], ["cases.id"], name=op.f("fk_calendar_activities_case_id_cases"), ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["client_id"], ["clients.id"], name=op.f("fk_calendar_activities_client_id_clients"), ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["company_id"], ["companies.id"], name=op.f("fk_calendar_activities_company_id_companies"), ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["creator_id"], ["users.id"], name=op.f("fk_calendar_activities_creator_id_users"), ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_calendar_activities")),
    )
    op.create_index(op.f("ix_calendar_activities_company_id"), "calendar_activities", ["company_id"], unique=False)
    op.create_index(op.f("ix_calendar_activities_end_at"), "calendar_activities", ["end_at"], unique=False)
    op.create_index(op.f("ix_calendar_activities_start_at"), "calendar_activities", ["start_at"], unique=False)
    op.create_index(op.f("ix_calendar_activities_type"), "calendar_activities", ["type"], unique=False)
    op.create_table(
        "folders",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("parent_id", sa.UUID(), nullable=True),
        sa.Column("case_id", sa.UUID(), nullable=True),
        sa.Column("created_by_id", sa.Uuid(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(["case_id"], ["cases.id"], name=op.f("fk_folders_case_id_cases"), ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["created_by_id"], ["users.id"], name=op.f("fk_folders_created_by_id_users"), ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["parent_id"], ["folders.id"], name=op.f("fk_folders_parent_id_folders"), ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_folders")),
    )
    op.create_index(op.f("ix_folders_case_id"), "folders", ["case_id"], unique=False)
    op.create_index(op.f("ix_folders_created_by_id"), "folders", ["created_by_id"], unique=False)
    op.create_index(op.f("ix_folders_parent_id"), "folders", ["parent_id"], unique=False)
    op.create_table(
        "mail_messages",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("external_message_id", sa.String(length=500), nullable=True),
        sa.Column("thread_id", sa.UUID(), nullable=True),
        sa.Column("parent_id", sa.UUID(), nullable=True),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("case_id", sa.UUID(), nullable=True),
        sa.Column("sender_email", sa.String(length=255), nullable=False),
        sa.Column("sender_name", sa.String(length=255), nullable=True),
        sa.Column("subject", sa.Text(), nullable=True),
        sa.Column(
            "message_type", sa.Enum("INCOMING", "OUTGOING", "SYSTEM_NOTIFICATION", name="mailmessagetype", native_enum=False), nullable=False
        ),
        sa.Column(
            "status",
            sa.Enum("DRAFT", "QUEUED", "SENDING", "SENT", "DELIVERED", "ERROR", "FAILED", name="mailmessagestatus", native_enum=False),
            nullable=False,
        ),
        sa.Column("is_read", sa.Boolean(), server_default="false", nullable=False),
        sa.Column("is_important", sa.Boolean(), server_default="false", nullable=False),
        sa.Column("is_starred", sa.Boolean(), server_default="false", nullable=False),
        sa.Column("is_spam", sa.Boolean(), server_default="false", nullable=False),
        sa.Column("is_archived", sa.Boolean(), server_default="false", nullable=False),
        sa.Column("is_deleted", sa.Boolean(), server_default="false", nullable=False),
        sa.Column("size_bytes", sa.BigInteger(), nullable=True),
        sa.Column("processed_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(["case_id"], ["cases.id"], name=op.f("fk_mail_messages_case_id_cases"), ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["parent_id"], ["mail_messages.id"], name=op.f("fk_mail_messages_parent_id_mail_messages"), ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], name=op.f("fk_mail_messages_user_id_users"), ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_mail_messages")),
    )
    op.create_index(op.f("ix_mail_messages_external_message_id"), "mail_messages", ["external_message_id"], unique=False)
    op.create_index(
        "ix_mail_messages_subject_search",
        "mail_messages",
        [sa.literal_column("to_tsvector('russian', subject)")],
        unique=False,
        postgresql_using="gin",
    )
    op.create_index(op.f("ix_mail_messages_thread_id"), "mail_messages", ["thread_id"], unique=False)
    op.create_index("ix_mail_messages_user_inbox", "mail_messages", ["user_id", "is_deleted", "is_spam", "processed_at"], unique=False)
    op.create_index("ix_mail_messages_user_unread", "mail_messages", ["user_id", "is_read", "is_deleted"], unique=False)
    op.create_table(
        "calendar_event_attendees",
        sa.Column("activity_id", sa.UUID(), nullable=False),
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(
            ["activity_id"],
            ["calendar_activities.id"],
            name=op.f("fk_calendar_event_attendees_activity_id_calendar_activities"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], name=op.f("fk_calendar_event_attendees_user_id_users"), ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("activity_id", "user_id", name=op.f("pk_calendar_event_attendees")),
    )
    op.create_table(
        "documents",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("case_id", sa.UUID(), nullable=True),
        sa.Column("folder_id", sa.UUID(), nullable=True),
        sa.Column("uploaded_by_id", sa.Uuid(), nullable=True),
        sa.Column("title", sa.Text(), nullable=False),
        sa.Column("original_filename", sa.Text(), nullable=False),
        sa.Column("file_path", sa.Text(), nullable=False),
        sa.Column("file_size", sa.BigInteger(), nullable=False),
        sa.Column("mime_type", sa.String(length=100), nullable=False),
        sa.Column("file_extension", sa.String(length=10), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("is_archived", sa.Boolean(), server_default="false", nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(["case_id"], ["cases.id"], name=op.f("fk_documents_case_id_cases"), ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["folder_id"], ["folders.id"], name=op.f("fk_documents_folder_id_folders"), ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["uploaded_by_id"], ["users.id"], name=op.f("fk_documents_uploaded_by_id_users"), ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_documents")),
    )
    op.create_index(op.f("ix_documents_case_id"), "documents", ["case_id"], unique=False)
    op.create_index(op.f("ix_documents_folder_id"), "documents", ["folder_id"], unique=False)
    op.create_index(op.f("ix_documents_uploaded_by_id"), "documents", ["uploaded_by_id"], unique=False)
    op.create_table(
        "mail_attachments",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("message_id", sa.UUID(), nullable=False),
        sa.Column("filename", sa.String(length=500), nullable=False),
        sa.Column("content_type", sa.String(length=100), nullable=False),
        sa.Column("file_size", sa.BigInteger(), nullable=False),
        sa.Column("stored_path", sa.Text(), nullable=False),
        sa.Column("attachment_id", sa.String(length=255), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(
            ["message_id"], ["mail_messages.id"], name=op.f("fk_mail_attachments_message_id_mail_messages"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_mail_attachments")),
    )
    op.create_index(op.f("ix_mail_attachments_message_id"), "mail_attachments", ["message_id"], unique=False)
    op.create_table(
        "mail_contents",
        sa.Column("message_id", sa.UUID(), nullable=False),
        sa.Column("body_text", sa.Text(), nullable=True),
        sa.Column("body_html", sa.Text(), nullable=True),
        sa.ForeignKeyConstraint(["message_id"], ["mail_messages.id"], name=op.f("fk_mail_contents_message_id_mail_messages"), ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("message_id", name=op.f("pk_mail_contents")),
    )
    op.create_table(
        "mail_recipients",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("message_id", sa.UUID(), nullable=False),
        sa.Column("email_address", sa.String(length=255), nullable=False),
        sa.Column("recipient_type", sa.Enum("TO", "CC", "BCC", name="mailrecipienttype", native_enum=False), nullable=False),
        sa.Column("name", sa.Text(), nullable=True),
        sa.ForeignKeyConstraint(
            ["message_id"], ["mail_messages.id"], name=op.f("fk_mail_recipients_message_id_mail_messages"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_mail_recipients")),
    )
    op.create_index(op.f("ix_mail_recipients_email_address"), "mail_recipients", ["email_address"], unique=False)
    op.create_index("ix_mail_recipients_email_message", "mail_recipients", ["email_address", "message_id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_mail_recipients_email_message", table_name="mail_recipients")
    op.drop_index(op.f("ix_mail_recipients_email_address"), table_name="mail_recipients")
    op.drop_table("mail_recipients")
    op.drop_table("mail_contents")
    op.drop_index(op.f("ix_mail_attachments_message_id"), table_name="mail_attachments")
    op.drop_table("mail_attachments")
    op.drop_index(op.f("ix_documents_uploaded_by_id"), table_name="documents")
    op.drop_index(op.f("ix_documents_folder_id"), table_name="documents")
    op.drop_index(op.f("ix_documents_case_id"), table_name="documents")
    op.drop_table("documents")
    op.drop_table("calendar_event_attendees")
    op.drop_index("ix_mail_messages_user_unread", table_name="mail_messages")
    op.drop_index("ix_mail_messages_user_inbox", table_name="mail_messages")
    op.drop_index(op.f("ix_mail_messages_thread_id"), table_name="mail_messages")
    op.drop_index("ix_mail_messages_subject_search", table_name="mail_messages", postgresql_using="gin")
    op.drop_index(op.f("ix_mail_messages_external_message_id"), table_name="mail_messages")
    op.drop_table("mail_messages")
    op.drop_index(op.f("ix_folders_parent_id"), table_name="folders")
    op.drop_index(op.f("ix_folders_created_by_id"), table_name="folders")
    op.drop_index(op.f("ix_folders_case_id"), table_name="folders")
    op.drop_table("folders")
    op.drop_index(op.f("ix_calendar_activities_type"), table_name="calendar_activities")
    op.drop_index(op.f("ix_calendar_activities_start_at"), table_name="calendar_activities")
    op.drop_index(op.f("ix_calendar_activities_end_at"), table_name="calendar_activities")
    op.drop_index(op.f("ix_calendar_activities_company_id"), table_name="calendar_activities")
    op.drop_table("calendar_activities")
    op.drop_table("user_email_configs")
    op.drop_table("contacts")
    op.drop_index(op.f("ix_cases_status"), table_name="cases")
    op.drop_index("ix_cases_number_btree", table_name="cases")
    op.drop_index(op.f("ix_cases_number"), table_name="cases")
    op.drop_index(op.f("ix_cases_deleted_at"), table_name="cases")
    op.drop_index(op.f("ix_cases_deadline"), table_name="cases")
    op.drop_index("ix_cases_client_status", table_name="cases")
    op.drop_index("ix_cases_case_number_btree", table_name="cases")
    op.drop_index(op.f("ix_cases_case_number"), table_name="cases")
    op.drop_table("cases")
    op.drop_index("ix_users_full_name_prefix", table_name="users", postgresql_ops={"full_name": "text_pattern_ops"})
    op.drop_index(op.f("ix_users_email"), table_name="users")
    op.drop_table("users")
    op.drop_index("ix_clients_short_name_prefix", table_name="clients", postgresql_ops={"short_name": "text_pattern_ops"})
    op.drop_index("ix_clients_name_prefix", table_name="clients", postgresql_ops={"name": "text_pattern_ops"})
    op.drop_index(op.f("ix_clients_name"), table_name="clients")
    op.drop_index(op.f("ix_clients_inn"), table_name="clients")
    op.drop_index(op.f("ix_clients_company_id"), table_name="clients")
    op.drop_table("clients")
    op.drop_index(op.f("ix_companies_name"), table_name="companies")
    op.drop_index(op.f("ix_companies_inn"), table_name="companies")
    op.drop_table("companies")
    # ### end Alembic commands ###
