"""refactor_unify_mail_attachments_and_add_oversized_batches

Revision ID: 59504b913936
Revises: 7203cdc42206
Create Date: 2026-03-14 22:03:43.710567

"""

from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "59504b913936"
down_revision: str | Sequence[str] | None = "7203cdc42206"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "mail_oversized_batches",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("mail_message_id", sa.UUID(), nullable=False),
        sa.Column("share_token", sa.String(length=64), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("company_id", sa.UUID(), nullable=True),
        sa.ForeignKeyConstraint(
            ["company_id"], ["companies.id"], name=op.f("fk_mail_oversized_batches_company_id_companies"), ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(
            ["mail_message_id"], ["mail_messages.id"], name=op.f("fk_mail_oversized_batches_mail_message_id_mail_messages"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_mail_oversized_batches")),
    )
    op.create_index(op.f("ix_mail_oversized_batches_company_id"), "mail_oversized_batches", ["company_id"], unique=False)
    op.create_index(op.f("ix_mail_oversized_batches_mail_message_id"), "mail_oversized_batches", ["mail_message_id"], unique=False)
    op.create_index(op.f("ix_mail_oversized_batches_share_token"), "mail_oversized_batches", ["share_token"], unique=True)
    op.create_table(
        "mail_attachments",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("mail_message_id", sa.UUID(), nullable=True),
        sa.Column("batch_id", sa.UUID(), nullable=True),
        sa.Column("s3_key", sa.Text(), nullable=False),
        sa.Column("s3_bucket", sa.String(length=255), nullable=False),
        sa.Column("filename", sa.String(length=500), nullable=False),
        sa.Column("content_type", sa.String(length=100), nullable=False),
        sa.Column("file_size", sa.BigInteger(), nullable=False),
        sa.Column("attachment_id", sa.String(length=255), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("company_id", sa.UUID(), nullable=True),
        sa.ForeignKeyConstraint(
            ["batch_id"], ["mail_oversized_batches.id"], name=op.f("fk_mail_attachments_batch_id_mail_oversized_batches"), ondelete="SET NULL"
        ),
        sa.ForeignKeyConstraint(["company_id"], ["companies.id"], name=op.f("fk_mail_attachments_company_id_companies"), ondelete="CASCADE"),
        sa.ForeignKeyConstraint(
            ["mail_message_id"], ["mail_messages.id"], name=op.f("fk_mail_attachments_mail_message_id_mail_messages"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_mail_attachments")),
    )
    op.create_index(op.f("ix_mail_attachments_batch_id"), "mail_attachments", ["batch_id"], unique=False)
    op.create_index(op.f("ix_mail_attachments_company_id"), "mail_attachments", ["company_id"], unique=False)
    op.create_index("ix_mail_attachments_company_message", "mail_attachments", ["company_id", "mail_message_id"], unique=False)
    op.create_index(op.f("ix_mail_attachments_mail_message_id"), "mail_attachments", ["mail_message_id"], unique=False)
    op.drop_index(op.f("ix_mail_attachments_s3_company_id"), table_name="mail_attachments_s3")
    op.drop_index(op.f("ix_mail_attachments_s3_company_message"), table_name="mail_attachments_s3")
    op.drop_index(op.f("ix_mail_attachments_s3_mail_message_id"), table_name="mail_attachments_s3")
    op.drop_table("mail_attachments_s3")
    op.drop_index(
        op.f("ix_mail_messages_subject_gin"), table_name="mail_messages", postgresql_ops={"subject": "gin_trgm_ops"}, postgresql_using="gin"
    )
    op.drop_index(op.f("ix_mail_sync_states_lookup"), table_name="mail_sync_states")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f("ix_mail_sync_states_lookup"), "mail_sync_states", ["company_id", "user_id", "folder", "last_synced_uid"], unique=False)
    op.create_index(
        op.f("ix_mail_messages_subject_gin"),
        "mail_messages",
        ["subject"],
        unique=False,
        postgresql_ops={"subject": "gin_trgm_ops"},
        postgresql_using="gin",
    )
    op.create_table(
        "mail_attachments_s3",
        sa.Column("id", sa.UUID(), autoincrement=False, nullable=False),
        sa.Column("mail_message_id", sa.UUID(), autoincrement=False, nullable=True),
        sa.Column("s3_key", sa.TEXT(), autoincrement=False, nullable=False),
        sa.Column("s3_bucket", sa.VARCHAR(length=255), autoincrement=False, nullable=False),
        sa.Column("filename", sa.VARCHAR(length=500), autoincrement=False, nullable=False),
        sa.Column("content_type", sa.VARCHAR(length=100), autoincrement=False, nullable=False),
        sa.Column("file_size", sa.BIGINT(), autoincrement=False, nullable=False),
        sa.Column("attachment_id", sa.VARCHAR(length=255), autoincrement=False, nullable=True),
        sa.Column("created_at", postgresql.TIMESTAMP(timezone=True), server_default=sa.text("now()"), autoincrement=False, nullable=False),
        sa.Column("company_id", sa.UUID(), autoincrement=False, nullable=True),
        sa.ForeignKeyConstraint(["company_id"], ["companies.id"], name=op.f("fk_mail_attachments_s3_company_id_companies"), ondelete="CASCADE"),
        sa.ForeignKeyConstraint(
            ["mail_message_id"], ["mail_messages.id"], name=op.f("fk_mail_attachments_s3_mail_message_id_mail_messages"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_mail_attachments_s3")),
    )
    op.create_index(op.f("ix_mail_attachments_s3_mail_message_id"), "mail_attachments_s3", ["mail_message_id"], unique=False)
    op.create_index(op.f("ix_mail_attachments_s3_company_message"), "mail_attachments_s3", ["company_id", "mail_message_id"], unique=False)
    op.create_index(op.f("ix_mail_attachments_s3_company_id"), "mail_attachments_s3", ["company_id"], unique=False)
    op.drop_index(op.f("ix_mail_attachments_mail_message_id"), table_name="mail_attachments")
    op.drop_index("ix_mail_attachments_company_message", table_name="mail_attachments")
    op.drop_index(op.f("ix_mail_attachments_company_id"), table_name="mail_attachments")
    op.drop_index(op.f("ix_mail_attachments_batch_id"), table_name="mail_attachments")
    op.drop_table("mail_attachments")
    op.drop_index(op.f("ix_mail_oversized_batches_share_token"), table_name="mail_oversized_batches")
    op.drop_index(op.f("ix_mail_oversized_batches_mail_message_id"), table_name="mail_oversized_batches")
    op.drop_index(op.f("ix_mail_oversized_batches_company_id"), table_name="mail_oversized_batches")
    op.drop_table("mail_oversized_batches")
    # ### end Alembic commands ###
