"""add delete documents

Revision ID: 5c79d35dd7d8
Revises: e869a982bd69
Create Date: 2026-05-18 20:57:14.235995

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "5c79d35dd7d8"
down_revision: str | Sequence[str] | None = "e869a982bd69"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("documents", sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True))
    op.add_column("documents", sa.Column("is_deleted", sa.Boolean(), server_default="false", nullable=False))
    op.create_index(op.f("ix_documents_deleted_at"), "documents", ["deleted_at"], unique=False)
    op.create_index(op.f("ix_documents_is_deleted"), "documents", ["is_deleted"], unique=False)
    op.add_column("folders", sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True))
    op.add_column("folders", sa.Column("is_deleted", sa.Boolean(), server_default="false", nullable=False))
    op.create_index(op.f("ix_folders_deleted_at"), "folders", ["deleted_at"], unique=False)
    op.create_index(op.f("ix_folders_is_deleted"), "folders", ["is_deleted"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_folders_is_deleted"), table_name="folders")
    op.drop_index(op.f("ix_folders_deleted_at"), table_name="folders")
    op.drop_column("folders", "is_deleted")
    op.drop_column("folders", "deleted_at")
    op.drop_index(op.f("ix_documents_is_deleted"), table_name="documents")
    op.drop_index(op.f("ix_documents_deleted_at"), table_name="documents")
    op.drop_column("documents", "is_deleted")
    op.drop_column("documents", "deleted_at")
    # ### end Alembic commands ###
