"""add table MailAttachmentS3

Revision ID: 6e0c6b4c3e0a
Revises: cadd8090f399
Create Date: 2026-03-09 16:53:12.665109

"""

from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "6e0c6b4c3e0a"
down_revision: str | Sequence[str] | None = "cadd8090f399"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    op.execute("CREATE EXTENSION IF NOT EXISTS pg_trgm")

    op.create_table(
        "mail_attachments_s3",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("mail_message_id", sa.UUID(), nullable=True),
        sa.Column("s3_key", sa.Text(), nullable=False),
        sa.Column("s3_bucket", sa.String(length=255), nullable=False),
        sa.Column("filename", sa.String(length=500), nullable=False),
        sa.Column("content_type", sa.String(length=100), nullable=False),
        sa.Column("file_size", sa.BigInteger(), nullable=False),
        sa.Column("attachment_id", sa.String(length=255), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("company_id", sa.UUID(), nullable=True),
        sa.ForeignKeyConstraint(["company_id"], ["companies.id"], name=op.f("fk_mail_attachments_s3_company_id_companies"), ondelete="CASCADE"),
        sa.ForeignKeyConstraint(
            ["mail_message_id"], ["mail_messages.id"], name=op.f("fk_mail_attachments_s3_mail_message_id_mail_messages"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_mail_attachments_s3")),
    )
    op.create_index(op.f("ix_mail_attachments_s3_company_id"), "mail_attachments_s3", ["company_id"], unique=False)
    op.create_index("ix_mail_attachments_s3_company_message", "mail_attachments_s3", ["company_id", "mail_message_id"], unique=False)
    op.create_index(op.f("ix_mail_attachments_s3_mail_message_id"), "mail_attachments_s3", ["mail_message_id"], unique=False)

    op.drop_index(op.f("ix_mail_attachments_message_id"), table_name="mail_attachments")
    op.drop_table("mail_attachments")

    op.drop_index(op.f("ix_case_experts_user_id"), table_name="case_experts")

    op.add_column("mail_messages", sa.Column("reply_to", sa.String(length=255), nullable=True))
    op.add_column(
        "mail_messages",
        sa.Column(
            "folder",
            sa.Enum("INBOX", "SENT", "DRAFTS", "SPAM", "TRASH", name="mailfolder", native_enum=False),
            server_default="inbox",
            nullable=False,
        ),
    )
    op.add_column("mail_messages", sa.Column("imap_uid", sa.BigInteger(), nullable=True))
    op.add_column("mail_messages", sa.Column("sent_at", sa.DateTime(timezone=True), nullable=True))
    op.add_column("mail_messages", sa.Column("company_id", sa.UUID(), nullable=True))

    op.drop_index(op.f("ix_mail_messages_subject_search"), table_name="mail_messages", postgresql_using="gin")
    op.drop_index(op.f("ix_mail_messages_user_inbox"), table_name="mail_messages")
    op.drop_index(op.f("ix_mail_messages_user_unread"), table_name="mail_messages")

    op.create_index("ix_mail_messages_company_folder", "mail_messages", ["company_id", "folder", "is_deleted", "sent_at"], unique=False)
    op.create_index(op.f("ix_mail_messages_company_id"), "mail_messages", ["company_id"], unique=False)
    op.create_index("ix_mail_messages_company_unread", "mail_messages", ["company_id", "is_read", "is_deleted"], unique=False)
    op.create_index(op.f("ix_mail_messages_folder"), "mail_messages", ["folder"], unique=False)
    op.create_index(op.f("ix_mail_messages_imap_uid"), "mail_messages", ["imap_uid"], unique=False)
    op.create_index(op.f("ix_mail_messages_sent_at"), "mail_messages", ["sent_at"], unique=False)

    op.create_index(
        "ix_mail_messages_subject_gin",
        "mail_messages",
        ["subject"],
        unique=False,
        postgresql_using="gin",
        postgresql_ops={"subject": "gin_trgm_ops"},
    )

    op.create_index(op.f("ix_mail_messages_user_id"), "mail_messages", ["user_id"], unique=False)
    op.create_foreign_key(op.f("fk_mail_messages_company_id_companies"), "mail_messages", "companies", ["company_id"], ["id"], ondelete="CASCADE")


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f("fk_mail_messages_company_id_companies"), "mail_messages", type_="foreignkey")
    op.drop_index(op.f("ix_mail_messages_user_id"), table_name="mail_messages")
    op.drop_index("ix_mail_messages_subject_gin", table_name="mail_messages", postgresql_using="gin", postgresql_ops={"subject": "gin_trgm_ops"})
    op.drop_index(op.f("ix_mail_messages_sent_at"), table_name="mail_messages")
    op.drop_index(op.f("ix_mail_messages_imap_uid"), table_name="mail_messages")
    op.drop_index(op.f("ix_mail_messages_folder"), table_name="mail_messages")
    op.drop_index("ix_mail_messages_company_unread", table_name="mail_messages")
    op.drop_index(op.f("ix_mail_messages_company_id"), table_name="mail_messages")
    op.drop_index("ix_mail_messages_company_folder", table_name="mail_messages")
    op.create_index(op.f("ix_mail_messages_user_unread"), "mail_messages", ["user_id", "is_read", "is_deleted"], unique=False)
    op.create_index(op.f("ix_mail_messages_user_inbox"), "mail_messages", ["user_id", "is_deleted", "is_spam", "processed_at"], unique=False)
    op.create_index(
        op.f("ix_mail_messages_subject_search"),
        "mail_messages",
        [sa.literal_column("to_tsvector('russian'::regconfig, subject)")],
        unique=False,
        postgresql_using="gin",
    )
    op.drop_column("mail_messages", "company_id")
    op.drop_column("mail_messages", "sent_at")
    op.drop_column("mail_messages", "imap_uid")
    op.drop_column("mail_messages", "folder")
    op.drop_column("mail_messages", "reply_to")
    op.create_index(op.f("ix_case_experts_user_id"), "case_experts", ["user_id"], unique=False)
    op.create_table(
        "mail_attachments",
        sa.Column("id", sa.UUID(), autoincrement=False, nullable=False),
        sa.Column("message_id", sa.UUID(), autoincrement=False, nullable=False),
        sa.Column("filename", sa.VARCHAR(length=500), autoincrement=False, nullable=False),
        sa.Column("content_type", sa.VARCHAR(length=100), autoincrement=False, nullable=False),
        sa.Column("file_size", sa.BIGINT(), autoincrement=False, nullable=False),
        sa.Column("stored_path", sa.TEXT(), autoincrement=False, nullable=False),
        sa.Column("attachment_id", sa.VARCHAR(length=255), autoincrement=False, nullable=False),
        sa.Column("created_at", postgresql.TIMESTAMP(timezone=True), server_default=sa.text("now()"), autoincrement=False, nullable=False),
        sa.ForeignKeyConstraint(
            ["message_id"], ["mail_messages.id"], name=op.f("fk_mail_attachments_message_id_mail_messages"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_mail_attachments")),
    )
    op.create_index(op.f("ix_mail_attachments_message_id"), "mail_attachments", ["message_id"], unique=False)
    op.drop_index(op.f("ix_mail_attachments_s3_mail_message_id"), table_name="mail_attachments_s3")
    op.drop_index("ix_mail_attachments_s3_company_message", table_name="mail_attachments_s3")
    op.drop_index(op.f("ix_mail_attachments_s3_company_id"), table_name="mail_attachments_s3")
    op.drop_table("mail_attachments_s3")
    # ### end Alembic commands ###
