"""add client id contact

Revision ID: 6ff48837f73a
Revises: eaf9185c2fad
Create Date: 2026-02-21 19:34:30.295429

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "6ff48837f73a"
down_revision: str | Sequence[str] | None = "eaf9185c2fad"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("contacts", sa.Column("company_id", sa.UUID(), nullable=True))
    op.create_index(op.f("ix_contacts_company_id"), "contacts", ["company_id"], unique=False)
    op.create_foreign_key(op.f("fk_contacts_company_id_companies"), "contacts", "companies", ["company_id"], ["id"], ondelete="CASCADE")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f("fk_contacts_company_id_companies"), "contacts", type_="foreignkey")
    op.drop_index(op.f("ix_contacts_company_id"), table_name="contacts")
    op.drop_column("contacts", "company_id")
    # ### end Alembic commands ###
