"""add mail_outbox table

Revision ID: 70c4f176c9cf
Revises: 1405121c5549
Create Date: 2026-03-19 08:43:59.932261

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "70c4f176c9cf"
down_revision: str | Sequence[str] | None = "1405121c5549"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "mail_outbox",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("mail_message_id", sa.UUID(), nullable=False),
        sa.Column("external_message_id", sa.String(length=500), nullable=False),
        sa.Column("status", sa.Enum("PENDING", "DONE", "FAILED", name="mailoutboxstatus", native_enum=False), nullable=False),
        sa.Column("attempts", sa.Integer(), server_default="0", nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("last_checked_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("company_id", sa.UUID(), nullable=True),
        sa.ForeignKeyConstraint(["company_id"], ["companies.id"], name=op.f("fk_mail_outbox_company_id_companies"), ondelete="CASCADE"),
        sa.ForeignKeyConstraint(
            ["mail_message_id"], ["mail_messages.id"], name=op.f("fk_mail_outbox_mail_message_id_mail_messages"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_mail_outbox")),
    )
    op.create_index(op.f("ix_mail_outbox_company_id"), "mail_outbox", ["company_id"], unique=False)
    op.create_index(op.f("ix_mail_outbox_mail_message_id"), "mail_outbox", ["mail_message_id"], unique=False)
    op.create_index(op.f("ix_mail_outbox_status"), "mail_outbox", ["status"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_mail_outbox_status"), table_name="mail_outbox")
    op.drop_index(op.f("ix_mail_outbox_mail_message_id"), table_name="mail_outbox")
    op.drop_index(op.f("ix_mail_outbox_company_id"), table_name="mail_outbox")
    op.drop_table("mail_outbox")
    # ### end Alembic commands ###
