"""Add mail_sync_states table

Revision ID: 7203cdc42206
Revises: 6e0c6b4c3e0a
Create Date: 2026-03-09 17:39:33.887099

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "7203cdc42206"
down_revision: str | Sequence[str] | None = "6e0c6b4c3e0a"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "mail_sync_states",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("folder", sa.String(length=50), server_default="inbox", nullable=False),
        sa.Column("last_synced_uid", sa.BigInteger(), server_default="0", nullable=False),
        sa.Column("last_synced_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("company_id", sa.UUID(), nullable=True),
        sa.ForeignKeyConstraint(["company_id"], ["companies.id"], name=op.f("fk_mail_sync_states_company_id_companies"), ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], name=op.f("fk_mail_sync_states_user_id_users"), ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_mail_sync_states")),
    )
    op.create_index(op.f("ix_mail_sync_states_company_id"), "mail_sync_states", ["company_id"], unique=False)
    op.create_index(op.f("ix_mail_sync_states_folder"), "mail_sync_states", ["folder"], unique=False)
    op.create_index("ix_mail_sync_states_lookup", "mail_sync_states", ["company_id", "user_id", "folder", "last_synced_uid"], unique=False)
    op.create_index("ix_mail_sync_states_unique", "mail_sync_states", ["company_id", "user_id", "folder"], unique=True)
    op.create_index(op.f("ix_mail_sync_states_user_id"), "mail_sync_states", ["user_id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_mail_sync_states_user_id"), table_name="mail_sync_states")
    op.drop_index("ix_mail_sync_states_unique", table_name="mail_sync_states")
    op.drop_index("ix_mail_sync_states_lookup", table_name="mail_sync_states")
    op.drop_index(op.f("ix_mail_sync_states_folder"), table_name="mail_sync_states")
    op.drop_index(op.f("ix_mail_sync_states_company_id"), table_name="mail_sync_states")
    op.drop_table("mail_sync_states")
    # ### end Alembic commands ###
