"""add total_cases and active_cases

Revision ID: 82a6eee35c90
Revises: a17e9e036b7b
Create Date: 2026-05-21 20:48:21.206563

"""

from collections.abc import Sequence

# revision identifiers, used by Alembic.
revision: str = "82a6eee35c90"
down_revision: str | Sequence[str] | None = "a17e9e036b7b"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
