"""Add legal_entity_type to clients

Revision ID: a17e9e036b7b
Revises: 51030402f484
Create Date: 2026-05-21 16:33:39.944366

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "a17e9e036b7b"
down_revision: str | Sequence[str] | None = "51030402f484"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("clients", sa.Column("legal_entity_type", sa.Enum("OOO", "IP", name="legalentitytype", native_enum=False), nullable=True))
    op.create_index(op.f("ix_clients_legal_entity_type"), "clients", ["legal_entity_type"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_clients_legal_entity_type"), table_name="clients")
    op.drop_column("clients", "legal_entity_type")
    # ### end Alembic commands ###
