"""add_expert_and_documents

Revision ID: a43fbd40fbe3
Revises: c22bd4f05ce1
Create Date: 2026-01-20 09:47:02.399982

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "a43fbd40fbe3"
down_revision: str | Sequence[str] | None = "c22bd4f05ce1"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "experts",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("full_name", sa.String(length=255), nullable=False),
        sa.Column("specialization", sa.String(length=100), nullable=True),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_experts")),
    )
    op.create_table(
        "documents",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("case_id", sa.UUID(), nullable=False),
        sa.Column("title", sa.String(length=255), nullable=False),
        sa.Column("file_path", sa.Text(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["case_id"],
            ["cases.id"],
            name=op.f("fk_documents_case_id_cases"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_documents")),
    )
    op.create_index(
        op.f("ix_documents_case_id"), "documents", ["case_id"], unique=False
    )
    op.alter_column(
        "cases",
        "assigned_expert_id",
        existing_type=sa.VARCHAR(length=50),
        type_=sa.UUID(),
        existing_nullable=True,
        postgresql_using="assigned_expert_id::uuid",
    )
    op.create_foreign_key(
        op.f("fk_cases_assigned_expert_id_experts"),
        "cases",
        "experts",
        ["assigned_expert_id"],
        ["id"],
        ondelete="SET NULL",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        op.f("fk_cases_assigned_expert_id_experts"), "cases", type_="foreignkey"
    )
    op.alter_column(
        "cases",
        "assigned_expert_id",
        existing_type=sa.UUID(),
        type_=sa.VARCHAR(length=50),
        existing_nullable=True,
    )
    op.drop_index(op.f("ix_documents_case_id"), table_name="documents")
    op.drop_table("documents")
    op.drop_table("experts")
    # ### end Alembic commands ###
