"""add models calendar

Revision ID: a6ad70184220
Revises: 40aad378fece
Create Date: 2026-01-28 15:00:48.174790

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "a6ad70184220"
down_revision: str | Sequence[str] | None = "40aad378fece"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "calendar_activities",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("type", sa.Enum("EVENT", "TASK", name="activitytype", native_enum=False), nullable=False),
        sa.Column("company_id", sa.UUID(), nullable=False),
        sa.Column("creator_id", sa.Uuid(), nullable=True),
        sa.Column("title", sa.String(length=255), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("color", sa.String(length=20), nullable=True),
        sa.Column("start_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("end_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("all_day", sa.Boolean(), nullable=False),
        sa.Column("is_completed", sa.Boolean(), nullable=False),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("location", sa.String(length=500), nullable=True),
        sa.Column("status", sa.Enum("SCHEDULED", "CANCELLED", name="eventstatus", native_enum=False), nullable=False),
        sa.Column("case_id", sa.UUID(), nullable=True),
        sa.Column("client_id", sa.UUID(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(["case_id"], ["cases.id"], name=op.f("fk_calendar_activities_case_id_cases"), ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["client_id"], ["clients.id"], name=op.f("fk_calendar_activities_client_id_clients"), ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["company_id"], ["companies.id"], name=op.f("fk_calendar_activities_company_id_companies"), ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["creator_id"], ["users.id"], name=op.f("fk_calendar_activities_creator_id_users"), ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_calendar_activities")),
    )
    op.create_index(op.f("ix_calendar_activities_company_id"), "calendar_activities", ["company_id"], unique=False)
    op.create_index(op.f("ix_calendar_activities_end_at"), "calendar_activities", ["end_at"], unique=False)
    op.create_index(op.f("ix_calendar_activities_start_at"), "calendar_activities", ["start_at"], unique=False)
    op.create_index(op.f("ix_calendar_activities_type"), "calendar_activities", ["type"], unique=False)
    op.create_table(
        "calendar_event_attendees",
        sa.Column("activity_id", sa.UUID(), nullable=False),
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(
            ["activity_id"],
            ["calendar_activities.id"],
            name=op.f("fk_calendar_event_attendees_activity_id_calendar_activities"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], name=op.f("fk_calendar_event_attendees_user_id_users"), ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("activity_id", "user_id", name=op.f("pk_calendar_event_attendees")),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("calendar_event_attendees")
    op.drop_index(op.f("ix_calendar_activities_type"), table_name="calendar_activities")
    op.drop_index(op.f("ix_calendar_activities_start_at"), table_name="calendar_activities")
    op.drop_index(op.f("ix_calendar_activities_end_at"), table_name="calendar_activities")
    op.drop_index(op.f("ix_calendar_activities_company_id"), table_name="calendar_activities")
    op.drop_table("calendar_activities")
    # ### end Alembic commands ###
