"""remove_expert_painting_and_archive_status

Revision ID: ab18b4f42ebb
Revises: aef5950fa9b7
Create Date: 2026-04-05 17:06:41.550749

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "ab18b4f42ebb"
down_revision: str | Sequence[str] | None = "aef5950fa9b7"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("cases", "expert_painting")
    op.drop_column("cases", "archive_status")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("cases", sa.Column("archive_status", sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column("cases", sa.Column("expert_painting", sa.TEXT(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
