"""add fts search vectors and indexes for mail

Revision ID: aef5950fa9b7
Revises: 1133d8c66251
Create Date: 2026-04-04 12:13:03.198902

"""

from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "aef5950fa9b7"
down_revision: str | Sequence[str] | None = "1133d8c66251"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_mail_outbox_company_id"), table_name="mail_outbox")
    op.drop_index(op.f("ix_mail_outbox_mail_message_id"), table_name="mail_outbox")
    op.drop_index(op.f("ix_mail_outbox_status"), table_name="mail_outbox")
    op.drop_table("mail_outbox")
    op.add_column(
        "mail_contents",
        sa.Column(
            "search_vector", postgresql.TSVECTOR(), sa.Computed("to_tsvector('russian', coalesce(body_text, ''))", persisted=True), nullable=False
        ),
    )
    op.create_index("ix_mail_contents_search_vector", "mail_contents", ["search_vector"], unique=False, postgresql_using="gin")
    op.add_column(
        "mail_messages",
        sa.Column(
            "search_vector",
            postgresql.TSVECTOR(),
            sa.Computed(
                (
                    "setweight(to_tsvector('russian', coalesce(subject, '')), 'A') || "
                    "setweight(to_tsvector('russian', coalesce(sender_name, '')), 'B') || "
                    "setweight(to_tsvector('russian', coalesce(sender_email, '')), 'C')"
                ),
                persisted=True,
            ),
            nullable=False,
        ),
    )
    op.create_index("ix_mail_messages_search_vector", "mail_messages", ["search_vector"], unique=False, postgresql_using="gin")
    op.create_index(
        "ix_mail_messages_thread_search", "mail_messages", ["company_id", "thread_id", "folder", "is_deleted", "sent_at"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_mail_messages_thread_search", table_name="mail_messages")
    op.drop_index("ix_mail_messages_search_vector", table_name="mail_messages", postgresql_using="gin")
    op.drop_column("mail_messages", "search_vector")
    op.drop_index("ix_mail_contents_search_vector", table_name="mail_contents", postgresql_using="gin")
    op.drop_column("mail_contents", "search_vector")
    op.create_table(
        "mail_outbox",
        sa.Column("id", sa.UUID(), autoincrement=False, nullable=False),
        sa.Column("mail_message_id", sa.UUID(), autoincrement=False, nullable=False),
        sa.Column("external_message_id", sa.VARCHAR(length=500), autoincrement=False, nullable=False),
        sa.Column("status", sa.VARCHAR(length=7), autoincrement=False, nullable=False),
        sa.Column("attempts", sa.INTEGER(), server_default=sa.text("0"), autoincrement=False, nullable=False),
        sa.Column("created_at", postgresql.TIMESTAMP(timezone=True), server_default=sa.text("now()"), autoincrement=False, nullable=False),
        sa.Column("last_checked_at", postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
        sa.Column("company_id", sa.UUID(), autoincrement=False, nullable=True),
        sa.ForeignKeyConstraint(["company_id"], ["companies.id"], name=op.f("fk_mail_outbox_company_id_companies"), ondelete="CASCADE"),
        sa.ForeignKeyConstraint(
            ["mail_message_id"], ["mail_messages.id"], name=op.f("fk_mail_outbox_mail_message_id_mail_messages"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_mail_outbox")),
    )
    op.create_index(op.f("ix_mail_outbox_status"), "mail_outbox", ["status"], unique=False)
    op.create_index(op.f("ix_mail_outbox_mail_message_id"), "mail_outbox", ["mail_message_id"], unique=False)
    op.create_index(op.f("ix_mail_outbox_company_id"), "mail_outbox", ["company_id"], unique=False)
    # ### end Alembic commands ###
