"""add_folders_table

Revision ID: b77e4c662fb4
Revises: c8bb8ec64fcf
Create Date: 2026-01-23 18:18:04.428976

"""

from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "b77e4c662fb4"
down_revision: str | Sequence[str] | None = "c8bb8ec64fcf"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "user_email_configs",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("smtp_host", sa.String(length=255), nullable=False),
        sa.Column("smtp_port", sa.Integer(), nullable=False),
        sa.Column("smtp_user", sa.String(length=255), nullable=False),
        sa.Column("smtp_password", sa.Text(), nullable=False),
        sa.Column("imap_host", sa.String(length=255), nullable=False),
        sa.Column("imap_port", sa.Integer(), nullable=False),
        sa.Column("imap_user", sa.String(length=255), nullable=False),
        sa.Column("imap_password", sa.Text(), nullable=False),
        sa.Column("last_sync_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("sync_enabled", sa.Boolean(), server_default="true", nullable=False),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], name=op.f("fk_user_email_configs_user_id_users"), ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_user_email_configs")),
        sa.UniqueConstraint("user_id", name=op.f("uq_user_email_configs_user_id")),
    )
    op.add_column("users", sa.Column("is_active", sa.Boolean(), server_default="false", nullable=False))
    op.add_column("users", sa.Column("can_authenticate", sa.Boolean(), server_default="true", nullable=False))
    op.add_column("users", sa.Column("last_login", sa.DateTime(timezone=True), nullable=True))
    op.add_column("users", sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False))
    op.alter_column("users", "hashed_password", existing_type=sa.VARCHAR(length=255), type_=sa.String(length=1024), existing_nullable=False)
    op.alter_column(
        "users", "settings", existing_type=postgresql.JSON(astext_type=sa.Text()), nullable=False, existing_server_default=sa.text("'{}'::json")
    )
    op.drop_column("users", "smtp_user")
    op.drop_column("users", "smtp_port")
    op.drop_column("users", "smtp_host")
    op.drop_column("users", "encrypted_smtp_password")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("users", sa.Column("encrypted_smtp_password", sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column("users", sa.Column("smtp_host", sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.add_column("users", sa.Column("smtp_port", sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column("users", sa.Column("smtp_user", sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.alter_column(
        "users", "settings", existing_type=postgresql.JSON(astext_type=sa.Text()), nullable=True, existing_server_default=sa.text("'{}'::json")
    )
    op.alter_column("users", "hashed_password", existing_type=sa.String(length=1024), type_=sa.VARCHAR(length=255), existing_nullable=False)
    op.drop_column("users", "updated_at")
    op.drop_column("users", "last_login")
    op.drop_column("users", "can_authenticate")
    op.drop_column("users", "is_active")
    op.drop_table("user_email_configs")
    # ### end Alembic commands ###
