"""add_trgm_indexes

Revision ID: ba070bf90de4
Revises: ab18b4f42ebb
Create Date: 2026-04-05 20:16:16.087268

"""

from collections.abc import Sequence

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "ba070bf90de4"
down_revision: str | Sequence[str] | None = "ab18b4f42ebb"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index("ix_clients_name_trgm", "clients", ["name"], unique=False, postgresql_using="gin", postgresql_ops={"name": "gin_trgm_ops"})
    op.create_index(
        "ix_clients_short_name_trgm",
        "clients",
        ["short_name"],
        unique=False,
        postgresql_using="gin",
        postgresql_ops={"short_name": "gin_trgm_ops"},
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_clients_short_name_trgm", table_name="clients", postgresql_using="gin", postgresql_ops={"short_name": "gin_trgm_ops"})
    op.drop_index("ix_clients_name_trgm", table_name="clients", postgresql_using="gin", postgresql_ops={"name": "gin_trgm_ops"})
    # ### end Alembic commands ###
