"""описание миграции

Revision ID: c22bd4f05ce1
Revises:
Create Date: 2026-01-19 19:18:49.961156

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "c22bd4f05ce1"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "clients",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("short_name", sa.String(length=100), nullable=True),
        sa.Column(
            "type",
            sa.Enum(
                "legal", "individual", "court", name="clienttype", native_enum=False
            ),
            nullable=False,
        ),
        sa.Column("inn", sa.String(length=12), nullable=True),
        sa.Column("email", sa.String(length=255), nullable=True),
        sa.Column("phone", sa.String(length=50), nullable=True),
        sa.Column("legal_address", sa.Text(), nullable=True),
        sa.Column("actual_address", sa.Text(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_clients_inn"), "clients", ["inn"], unique=True)
    op.create_index(op.f("ix_clients_name"), "clients", ["name"], unique=False)
    op.create_table(
        "cases",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("client_id", sa.UUID(), nullable=False),
        sa.Column("number", sa.String(length=50), nullable=False),
        sa.Column("case_number", sa.String(length=100), nullable=False),
        sa.Column("authority", sa.String(length=255), nullable=False),
        sa.Column("case_type", sa.String(length=100), nullable=False),
        sa.Column("object_type", sa.String(length=100), nullable=False),
        sa.Column("object_address", sa.Text(), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "archive",
                "in_work",
                "debt",
                "executed",
                "withdrawn",
                "cancelled",
                "fssp",
                name="casestatus",
                native_enum=False,
            ),
            nullable=False,
        ),
        sa.Column("assigned_expert_id", sa.String(length=50), nullable=True),
        sa.Column("start_date", sa.DateTime(timezone=True), nullable=False),
        sa.Column("deadline", sa.DateTime(timezone=True), nullable=False),
        sa.Column("completion_date", sa.DateTime(timezone=True), nullable=True),
        sa.Column("cost", sa.Numeric(precision=12, scale=2), nullable=False),
        sa.Column(
            "bank_transfer_amount",
            sa.Numeric(precision=12, scale=2),
            server_default="0.00",
            nullable=False,
        ),
        sa.Column(
            "cash_amount",
            sa.Numeric(precision=12, scale=2),
            server_default="0.00",
            nullable=False,
        ),
        sa.Column(
            "remaining_debt",
            sa.Numeric(precision=12, scale=2),
            server_default="0.00",
            nullable=False,
        ),
        sa.Column("plaintiff", sa.String(length=255), nullable=True),
        sa.Column("defendant", sa.String(length=255), nullable=True),
        sa.Column("expert_painting", sa.Text(), nullable=True),
        sa.Column("archive_status", sa.Text(), nullable=True),
        sa.Column("remarks", sa.Text(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(["client_id"], ["clients.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_cases_case_number"), "cases", ["case_number"], unique=True)
    op.create_index(
        "ix_cases_client_status", "cases", ["client_id", "status"], unique=False
    )
    op.create_index(op.f("ix_cases_deadline"), "cases", ["deadline"], unique=False)
    op.create_index(op.f("ix_cases_deleted_at"), "cases", ["deleted_at"], unique=False)
    op.create_index(op.f("ix_cases_number"), "cases", ["number"], unique=True)
    op.create_index(op.f("ix_cases_status"), "cases", ["status"], unique=False)
    op.create_table(
        "contacts",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("client_id", sa.UUID(), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("position", sa.String(length=255), nullable=True),
        sa.Column("email", sa.String(length=255), nullable=True),
        sa.Column("phone", sa.String(length=50), nullable=True),
        sa.Column("is_main", sa.Boolean(), server_default="false", nullable=False),
        sa.Column(
            "contact_type",
            sa.Enum(
                "legal_representative",
                "court_officer",
                "individual",
                name="contacttype",
                native_enum=False,
            ),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["client_id"], ["clients.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("contacts")
    op.drop_index(op.f("ix_cases_status"), table_name="cases")
    op.drop_index(op.f("ix_cases_number"), table_name="cases")
    op.drop_index(op.f("ix_cases_deleted_at"), table_name="cases")
    op.drop_index(op.f("ix_cases_deadline"), table_name="cases")
    op.drop_index("ix_cases_client_status", table_name="cases")
    op.drop_index(op.f("ix_cases_case_number"), table_name="cases")
    op.drop_table("cases")
    op.drop_index(op.f("ix_clients_name"), table_name="clients")
    op.drop_index(op.f("ix_clients_inn"), table_name="clients")
    op.drop_table("clients")
    # ### end Alembic commands ###
