"""add_folders_table

Revision ID: c8bb8ec64fcf
Revises: 2d7ad9e973ee
Create Date: 2026-01-22 21:23:44.398819

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "c8bb8ec64fcf"
down_revision: str | Sequence[str] | None = "2d7ad9e973ee"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "folders",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("parent_id", sa.UUID(), nullable=True),
        sa.Column("case_id", sa.UUID(), nullable=True),
        sa.Column("created_by_id", sa.UUID(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(["case_id"], ["cases.id"], name=op.f("fk_folders_case_id_cases"), ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["created_by_id"], ["users.id"], name=op.f("fk_folders_created_by_id_users"), ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["parent_id"], ["folders.id"], name=op.f("fk_folders_parent_id_folders"), ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_folders")),
    )
    op.create_index(op.f("ix_folders_case_id"), "folders", ["case_id"], unique=False)
    op.create_index(op.f("ix_folders_created_by_id"), "folders", ["created_by_id"], unique=False)
    op.create_index(op.f("ix_folders_parent_id"), "folders", ["parent_id"], unique=False)
    op.add_column("documents", sa.Column("folder_id", sa.UUID(), nullable=True))
    op.create_index(op.f("ix_documents_folder_id"), "documents", ["folder_id"], unique=False)
    op.create_foreign_key(op.f("fk_documents_folder_id_folders"), "documents", "folders", ["folder_id"], ["id"], ondelete="SET NULL")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f("fk_documents_folder_id_folders"), "documents", type_="foreignkey")
    op.drop_index(op.f("ix_documents_folder_id"), table_name="documents")
    op.drop_column("documents", "folder_id")
    op.drop_index(op.f("ix_folders_parent_id"), table_name="folders")
    op.drop_index(op.f("ix_folders_created_by_id"), table_name="folders")
    op.drop_index(op.f("ix_folders_case_id"), table_name="folders")
    op.drop_table("folders")
    # ### end Alembic commands ###
