"""add company_id colum for Tabel

Revision ID: d98438765d63
Revises: 57db10d915a6
Create Date: 2026-02-19 17:36:06.189034

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "d98438765d63"
down_revision: str | Sequence[str] | None = "57db10d915a6"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("cases", sa.Column("company_id", sa.UUID(), nullable=True))
    op.create_index(op.f("ix_cases_company_id"), "cases", ["company_id"], unique=False)
    op.create_foreign_key(op.f("fk_cases_company_id_companies"), "cases", "companies", ["company_id"], ["id"], ondelete="CASCADE")
    op.add_column("documents", sa.Column("company_id", sa.UUID(), nullable=True))
    op.create_index(op.f("ix_documents_company_id"), "documents", ["company_id"], unique=False)
    op.create_index("ix_documents_company_id_id", "documents", ["company_id", "id"], unique=False)
    op.create_foreign_key(op.f("fk_documents_company_id_companies"), "documents", "companies", ["company_id"], ["id"], ondelete="CASCADE")
    op.add_column("folders", sa.Column("company_id", sa.UUID(), nullable=True))
    op.create_index(op.f("ix_folders_company_id"), "folders", ["company_id"], unique=False)
    op.create_index("ix_folders_company_id_id", "folders", ["company_id", "id"], unique=False)
    op.create_foreign_key(op.f("fk_folders_company_id_companies"), "folders", "companies", ["company_id"], ["id"], ondelete="CASCADE")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f("fk_folders_company_id_companies"), "folders", type_="foreignkey")
    op.drop_index("ix_folders_company_id_id", table_name="folders")
    op.drop_index(op.f("ix_folders_company_id"), table_name="folders")
    op.drop_column("folders", "company_id")
    op.drop_constraint(op.f("fk_documents_company_id_companies"), "documents", type_="foreignkey")
    op.drop_index("ix_documents_company_id_id", table_name="documents")
    op.drop_index(op.f("ix_documents_company_id"), table_name="documents")
    op.drop_column("documents", "company_id")
    op.drop_constraint(op.f("fk_cases_company_id_companies"), "cases", type_="foreignkey")
    op.drop_index(op.f("ix_cases_company_id"), table_name="cases")
    op.drop_column("cases", "company_id")
    # ### end Alembic commands ###
