"""add_debit_field_to_cases

Revision ID: e869a982bd69
Revises: ba070bf90de4
Create Date: 2026-04-20 18:18:54.189822

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "e869a982bd69"
down_revision: str | Sequence[str] | None = "ba070bf90de4"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("cases", sa.Column("debit", sa.Numeric(precision=12, scale=2), server_default="0.00", nullable=False))
    op.create_index(op.f("ix_cases_debit"), "cases", ["debit"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_cases_debit"), table_name="cases")
    op.drop_column("cases", "debit")
    # ### end Alembic commands ###
