"""add_indexes_to_users_clients_cases_documents_folders

Revision ID: eaf9185c2fad
Revises: d98438765d63
Create Date: 2026-02-20 10:55:05.077230

"""

from collections.abc import Sequence

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "eaf9185c2fad"
down_revision: str | Sequence[str] | None = "d98438765d63"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_cases_client_status"), table_name="cases")
    op.create_index(op.f("ix_cases_assigned_user_id"), "cases", ["assigned_user_id"], unique=False)
    op.create_index(op.f("ix_cases_authority"), "cases", ["authority"], unique=False)
    op.create_index(op.f("ix_cases_case_type"), "cases", ["case_type"], unique=False)
    op.create_index(op.f("ix_cases_client_id"), "cases", ["client_id"], unique=False)
    op.create_index("ix_cases_company_id_assigned_user_id_status", "cases", ["company_id", "assigned_user_id", "status"], unique=False)
    op.create_index("ix_cases_company_id_client_id", "cases", ["company_id", "client_id"], unique=False)
    op.create_index("ix_cases_company_id_created_at", "cases", ["company_id", "created_at"], unique=False)
    op.create_index("ix_cases_company_id_deadline", "cases", ["company_id", "deadline"], unique=False)
    op.create_index("ix_cases_company_id_status", "cases", ["company_id", "status"], unique=False)
    op.create_index(op.f("ix_cases_completion_date"), "cases", ["completion_date"], unique=False)
    op.create_index(op.f("ix_cases_created_at"), "cases", ["created_at"], unique=False)
    op.create_index(op.f("ix_cases_defendant"), "cases", ["defendant"], unique=False)
    op.create_index(op.f("ix_cases_object_address"), "cases", ["object_address"], unique=False)
    op.create_index(op.f("ix_cases_object_type"), "cases", ["object_type"], unique=False)
    op.create_index(op.f("ix_cases_plaintiff"), "cases", ["plaintiff"], unique=False)
    op.create_index(op.f("ix_cases_start_date"), "cases", ["start_date"], unique=False)
    op.create_index("ix_clients_company_id_created_at", "clients", ["company_id", "created_at"], unique=False)
    op.create_index("ix_clients_company_id_inn", "clients", ["company_id", "inn"], unique=False)
    op.create_index("ix_clients_company_id_type", "clients", ["company_id", "type"], unique=False)
    op.create_index(op.f("ix_clients_created_at"), "clients", ["created_at"], unique=False)
    op.create_index(op.f("ix_clients_email"), "clients", ["email"], unique=False)
    op.create_index(op.f("ix_clients_phone"), "clients", ["phone"], unique=False)
    op.create_index(op.f("ix_clients_short_name"), "clients", ["short_name"], unique=False)
    op.create_index(op.f("ix_clients_type"), "clients", ["type"], unique=False)
    op.drop_index(op.f("ix_documents_company_id_id"), table_name="documents")
    op.create_index("ix_documents_company_id_case_id", "documents", ["company_id", "case_id"], unique=False)
    op.create_index("ix_documents_company_id_created_at", "documents", ["company_id", "created_at"], unique=False)
    op.create_index("ix_documents_company_id_folder_id", "documents", ["company_id", "folder_id"], unique=False)
    op.create_index("ix_documents_company_id_is_archived", "documents", ["company_id", "is_archived"], unique=False)
    op.create_index("ix_documents_company_id_mime_type", "documents", ["company_id", "mime_type"], unique=False)
    op.create_index(op.f("ix_documents_created_at"), "documents", ["created_at"], unique=False)
    op.create_index(op.f("ix_documents_file_extension"), "documents", ["file_extension"], unique=False)
    op.create_index(op.f("ix_documents_file_path"), "documents", ["file_path"], unique=True)
    op.create_index(op.f("ix_documents_is_archived"), "documents", ["is_archived"], unique=False)
    op.create_index(op.f("ix_documents_mime_type"), "documents", ["mime_type"], unique=False)
    op.create_index(op.f("ix_documents_title"), "documents", ["title"], unique=False)
    op.drop_index(op.f("ix_folders_company_id_id"), table_name="folders")
    op.create_index("ix_folders_company_id_case_id", "folders", ["company_id", "case_id"], unique=False)
    op.create_index("ix_folders_company_id_created_at", "folders", ["company_id", "created_at"], unique=False)
    op.create_index("ix_folders_company_id_name", "folders", ["company_id", "name"], unique=False)
    op.create_index("ix_folders_company_id_parent_id", "folders", ["company_id", "parent_id"], unique=False)
    op.create_index(op.f("ix_folders_created_at"), "folders", ["created_at"], unique=False)
    op.create_index(op.f("ix_folders_name"), "folders", ["name"], unique=False)
    op.create_index(op.f("ix_users_company_id"), "users", ["company_id"], unique=False)
    op.create_index("ix_users_company_id_can_authenticate", "users", ["company_id", "can_authenticate"], unique=False)
    op.create_index("ix_users_company_id_created_at", "users", ["company_id", "created_at"], unique=False)
    op.create_index("ix_users_company_id_email", "users", ["company_id", "email"], unique=False)
    op.create_index("ix_users_company_id_is_active", "users", ["company_id", "is_active"], unique=False)
    op.create_index("ix_users_company_id_last_login", "users", ["company_id", "last_login"], unique=False)
    op.create_index("ix_users_company_id_role", "users", ["company_id", "role"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_users_company_id_role", table_name="users")
    op.drop_index("ix_users_company_id_last_login", table_name="users")
    op.drop_index("ix_users_company_id_is_active", table_name="users")
    op.drop_index("ix_users_company_id_email", table_name="users")
    op.drop_index("ix_users_company_id_created_at", table_name="users")
    op.drop_index("ix_users_company_id_can_authenticate", table_name="users")
    op.drop_index(op.f("ix_users_company_id"), table_name="users")
    op.drop_index(op.f("ix_folders_name"), table_name="folders")
    op.drop_index(op.f("ix_folders_created_at"), table_name="folders")
    op.drop_index("ix_folders_company_id_parent_id", table_name="folders")
    op.drop_index("ix_folders_company_id_name", table_name="folders")
    op.drop_index("ix_folders_company_id_created_at", table_name="folders")
    op.drop_index("ix_folders_company_id_case_id", table_name="folders")
    op.create_index(op.f("ix_folders_company_id_id"), "folders", ["company_id", "id"], unique=False)
    op.drop_index(op.f("ix_documents_title"), table_name="documents")
    op.drop_index(op.f("ix_documents_mime_type"), table_name="documents")
    op.drop_index(op.f("ix_documents_is_archived"), table_name="documents")
    op.drop_index(op.f("ix_documents_file_path"), table_name="documents")
    op.drop_index(op.f("ix_documents_file_extension"), table_name="documents")
    op.drop_index(op.f("ix_documents_created_at"), table_name="documents")
    op.drop_index("ix_documents_company_id_mime_type", table_name="documents")
    op.drop_index("ix_documents_company_id_is_archived", table_name="documents")
    op.drop_index("ix_documents_company_id_folder_id", table_name="documents")
    op.drop_index("ix_documents_company_id_created_at", table_name="documents")
    op.drop_index("ix_documents_company_id_case_id", table_name="documents")
    op.create_index(op.f("ix_documents_company_id_id"), "documents", ["company_id", "id"], unique=False)
    op.drop_index(op.f("ix_clients_type"), table_name="clients")
    op.drop_index(op.f("ix_clients_short_name"), table_name="clients")
    op.drop_index(op.f("ix_clients_phone"), table_name="clients")
    op.drop_index(op.f("ix_clients_email"), table_name="clients")
    op.drop_index(op.f("ix_clients_created_at"), table_name="clients")
    op.drop_index("ix_clients_company_id_type", table_name="clients")
    op.drop_index("ix_clients_company_id_inn", table_name="clients")
    op.drop_index("ix_clients_company_id_created_at", table_name="clients")
    op.drop_index(op.f("ix_cases_start_date"), table_name="cases")
    op.drop_index(op.f("ix_cases_plaintiff"), table_name="cases")
    op.drop_index(op.f("ix_cases_object_type"), table_name="cases")
    op.drop_index(op.f("ix_cases_object_address"), table_name="cases")
    op.drop_index(op.f("ix_cases_defendant"), table_name="cases")
    op.drop_index(op.f("ix_cases_created_at"), table_name="cases")
    op.drop_index(op.f("ix_cases_completion_date"), table_name="cases")
    op.drop_index("ix_cases_company_id_status", table_name="cases")
    op.drop_index("ix_cases_company_id_deadline", table_name="cases")
    op.drop_index("ix_cases_company_id_created_at", table_name="cases")
    op.drop_index("ix_cases_company_id_client_id", table_name="cases")
    op.drop_index("ix_cases_company_id_assigned_user_id_status", table_name="cases")
    op.drop_index(op.f("ix_cases_client_id"), table_name="cases")
    op.drop_index(op.f("ix_cases_case_type"), table_name="cases")
    op.drop_index(op.f("ix_cases_authority"), table_name="cases")
    op.drop_index(op.f("ix_cases_assigned_user_id"), table_name="cases")
    op.create_index(op.f("ix_cases_client_status"), "cases", ["client_id", "status"], unique=False)
    # ### end Alembic commands ###
