"""fix model User and Document

Revision ID: ebc8060eb98a
Revises: 7100554be6e6
Create Date: 2026-01-21 23:19:17.302486

"""

from collections.abc import Sequence

# revision identifiers, used by Alembic.
revision: str = "ebc8060eb98a"
down_revision: str | Sequence[str] | None = "7100554be6e6"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
