"""fix_circular_dependency

Revision ID: eed984b8e42c
Revises: 12ecb4367fc3
Create Date: 2026-02-23 21:13:45.695845

"""

from collections.abc import Sequence

# revision identifiers, used by Alembic.
revision: str = "eed984b8e42c"
down_revision: str | Sequence[str] | None = "12ecb4367fc3"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
