"""Add judge_name to cases

Revision ID: f48b31059f9a
Revises: 6ff48837f73a
Create Date: 2026-02-22 21:46:07.096938

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "f48b31059f9a"
down_revision: str | Sequence[str] | None = "6ff48837f73a"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("cases", sa.Column("judge_name", sa.Text(), nullable=True))
    op.create_index(op.f("ix_cases_judge_name"), "cases", ["judge_name"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_cases_judge_name"), table_name="cases")
    op.drop_column("cases", "judge_name")
    # ### end Alembic commands ###
