"""add mails table

Revision ID: f833aefbc52a
Revises: 4c25d7102237
Create Date: 2026-01-24 20:58:50.353362

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "f833aefbc52a"
down_revision: str | Sequence[str] | None = "4c25d7102237"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "mail_messages",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("external_message_id", sa.String(length=500), nullable=True),
        sa.Column("thread_id", sa.UUID(), nullable=True),
        sa.Column("parent_id", sa.UUID(), nullable=True),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("case_id", sa.UUID(), nullable=True),
        sa.Column("sender_email", sa.String(length=255), nullable=False),
        sa.Column("sender_name", sa.String(length=255), nullable=True),
        sa.Column("subject", sa.String(length=1000), nullable=True),
        sa.Column(
            "message_type", sa.Enum("INCOMING", "OUTGOING", "SYSTEM_NOTIFICATION", name="mailmessagetype", native_enum=False), nullable=False
        ),
        sa.Column(
            "status",
            sa.Enum("DRAFT", "QUEUED", "SENDING", "SENT", "DELIVERED", "ERROR", "FAILED", name="mailmessagestatus", native_enum=False),
            nullable=False,
        ),
        sa.Column("is_read", sa.Boolean(), server_default="false", nullable=False),
        sa.Column("is_important", sa.Boolean(), server_default="false", nullable=False),
        sa.Column("is_starred", sa.Boolean(), server_default="false", nullable=False),
        sa.Column("is_spam", sa.Boolean(), server_default="false", nullable=False),
        sa.Column("is_archived", sa.Boolean(), server_default="false", nullable=False),
        sa.Column("is_deleted", sa.Boolean(), server_default="false", nullable=False),
        sa.Column("size_bytes", sa.BigInteger(), nullable=True),
        sa.Column("processed_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(["case_id"], ["cases.id"], name=op.f("fk_mail_messages_case_id_cases"), ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["parent_id"], ["mail_messages.id"], name=op.f("fk_mail_messages_parent_id_mail_messages"), ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], name=op.f("fk_mail_messages_user_id_users"), ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_mail_messages")),
    )
    op.create_index(op.f("ix_mail_messages_external_message_id"), "mail_messages", ["external_message_id"], unique=False)
    op.create_index(
        "ix_mail_messages_subject_search",
        "mail_messages",
        [sa.literal_column("to_tsvector('russian', subject)")],
        unique=False,
        postgresql_using="gin",
    )
    op.create_index(op.f("ix_mail_messages_thread_id"), "mail_messages", ["thread_id"], unique=False)
    op.create_index("ix_mail_messages_user_inbox", "mail_messages", ["user_id", "is_deleted", "is_spam", "processed_at"], unique=False)
    op.create_index("ix_mail_messages_user_unread", "mail_messages", ["user_id", "is_read", "is_deleted"], unique=False)
    op.create_table(
        "mail_attachments",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("message_id", sa.UUID(), nullable=False),
        sa.Column("filename", sa.String(length=500), nullable=False),
        sa.Column("content_type", sa.String(length=100), nullable=False),
        sa.Column("file_size", sa.BigInteger(), nullable=False),
        sa.Column("stored_path", sa.Text(), nullable=False),
        sa.Column("attachment_id", sa.String(length=255), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(
            ["message_id"], ["mail_messages.id"], name=op.f("fk_mail_attachments_message_id_mail_messages"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_mail_attachments")),
    )
    op.create_index(op.f("ix_mail_attachments_message_id"), "mail_attachments", ["message_id"], unique=False)
    op.create_table(
        "mail_contents",
        sa.Column("message_id", sa.UUID(), nullable=False),
        sa.Column("body_text", sa.Text(), nullable=True),
        sa.Column("body_html", sa.Text(), nullable=True),
        sa.ForeignKeyConstraint(["message_id"], ["mail_messages.id"], name=op.f("fk_mail_contents_message_id_mail_messages"), ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("message_id", name=op.f("pk_mail_contents")),
    )
    op.create_table(
        "mail_recipients",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("message_id", sa.UUID(), nullable=False),
        sa.Column("email_address", sa.String(length=255), nullable=False),
        sa.Column("recipient_type", sa.Enum("TO", "CC", "BCC", name="mailrecipienttype", native_enum=False), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=True),
        sa.ForeignKeyConstraint(
            ["message_id"], ["mail_messages.id"], name=op.f("fk_mail_recipients_message_id_mail_messages"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_mail_recipients")),
    )
    op.create_index(op.f("ix_mail_recipients_email_address"), "mail_recipients", ["email_address"], unique=False)
    op.create_index("ix_mail_recipients_email_message", "mail_recipients", ["email_address", "message_id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_mail_recipients_email_message", table_name="mail_recipients")
    op.drop_index(op.f("ix_mail_recipients_email_address"), table_name="mail_recipients")
    op.drop_table("mail_recipients")
    op.drop_table("mail_contents")
    op.drop_index(op.f("ix_mail_attachments_message_id"), table_name="mail_attachments")
    op.drop_table("mail_attachments")
    op.drop_index("ix_mail_messages_user_unread", table_name="mail_messages")
    op.drop_index("ix_mail_messages_user_inbox", table_name="mail_messages")
    op.drop_index(op.f("ix_mail_messages_thread_id"), table_name="mail_messages")
    op.drop_index("ix_mail_messages_subject_search", table_name="mail_messages", postgresql_using="gin")
    op.drop_index(op.f("ix_mail_messages_external_message_id"), table_name="mail_messages")
    op.drop_table("mail_messages")
    # ### end Alembic commands ###
